services:
  - type: web
    name: prezinko-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    rootDir: backend
    autoDeploy: true

  - type: web
    name: prezinko-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"   # âœ… Vite outputs to "dist"
    rootDir: frontend
    autoDeploy: true
